QDRANT_CLIENT_CONFIG:
   HOST: "localhost"
   PORT: 6333

DATA_INGESTION_CONFIG:
   IMAGES_DIR: "images_data" # Directory name within the data folder
   BATCH_SIZE: 1000 # Number of data points to be processed per BATCH
   DATA_LIMIT: 6000 # Number of data points to be fetched randomly from the dataset

MODEL_CONFIG:
   MODEL_ID: "openai/clip-vit-base-patch32"
   VECTOR_SIZE: 512